name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan ec2-34-238-240-19.compute-1.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to EC2 and Restart Flask
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@ec2-34-238-240-19.compute-1.amazonaws.com << 'EOF'
            cd /home/ubuntu/flask-app
            git pull origin main

            # Try systemd restart first
            if sudo systemctl is-active --quiet flask-app; then
              echo "Restarting flask-app via systemd..."
              sudo systemctl restart flask-app
            else
              echo "systemd not found or flask-app not registered, falling back to manual restart..."
              pkill -f app.py || echo "No running app.py found"
              nohup python3 app.py > log.txt 2>&1 &
            fi
          EOF
